# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\button.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets

from . import LOGGER, RESOURCE_PATH

class Ui_Button(object):
    def setupUi(self, Button):
        Button.setObjectName("Button")
        Button.resize(144, 80)
        Button.setMinimumSize(QtCore.QSize(144, 80))
        Button.setMaximumSize(QtCore.QSize(144, 80))
        self.gridLayout_2 = QtWidgets.QGridLayout(Button)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Button)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(RESOURCE_PATH, "cross-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(os.path.join(RESOURCE_PATH, "tick-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Button)
        QtCore.QMetaObject.connectSlotsByName(Button)

    def retranslateUi(self, Button):
        _translate = QtCore.QCoreApplication.translate
        Button.setWindowTitle(_translate("Button", "Button"))
        self.groupBox.setTitle(_translate("Button", "Button Name"))
