# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\display.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets

from . import RESOURCE_PATH

class Ui_Display(object):
    def setupUi(self, Display):
        Display.setObjectName("Display")
        Display.resize(166, 180)
        Display.setMinimumSize(QtCore.QSize(166, 180))
        Display.setMaximumSize(QtCore.QSize(166, 180))
        self.gridLayout = QtWidgets.QGridLayout(Display)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Display)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = QtWidgets.QLabel(self.groupBox)
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(os.path.join(RESOURCE_PATH, "..", "emotion/neutral.png")))
        self.image.setScaledContents(True)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Display)
        QtCore.QMetaObject.connectSlotsByName(Display)

    def retranslateUi(self, Display):
        _translate = QtCore.QCoreApplication.translate
        Display.setWindowTitle(_translate("Display", "Display"))
        self.groupBox.setTitle(_translate("Display", "Display Name"))

class Display(QtWidgets.QWidget, Ui_Display):
    """
    Display widget
    """
    def __init__(self, name, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.name = name
        self.groupBox.setTitle(name)

    def set_image(self, image):
        """
        Set the image to display
        """
        self.image.setPixmap(QtGui.QPixmap(image))
