# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\worker_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WorkerManager(object):
    def setupUi(self, WorkerManager):
        WorkerManager.setObjectName("WorkerManager")
        WorkerManager.resize(386, 243)
        WorkerManager.setMinimumSize(QtCore.QSize(386, 243))
        self.gridLayout = QtWidgets.QGridLayout(WorkerManager)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(WorkerManager)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.workerTable = QtWidgets.QTableWidget(self.groupBox)
        self.workerTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.workerTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.workerTable.setCornerButtonEnabled(False)
        self.workerTable.setObjectName("workerTable")
        self.workerTable.setColumnCount(2)
        self.workerTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.workerTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.workerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.workerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.workerTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.workerTable.setItem(0, 1, item)
        self.workerTable.horizontalHeader().setCascadingSectionResizes(True)
        self.workerTable.horizontalHeader().setDefaultSectionSize(150)
        self.workerTable.horizontalHeader().setMinimumSectionSize(150)
        self.workerTable.horizontalHeader().setStretchLastSection(True)
        self.workerTable.verticalHeader().setVisible(False)
        self.workerTable.verticalHeader().setMinimumSectionSize(30)
        self.verticalLayout.addWidget(self.workerTable)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(WorkerManager)
        QtCore.QMetaObject.connectSlotsByName(WorkerManager)

    def retranslateUi(self, WorkerManager):
        _translate = QtCore.QCoreApplication.translate
        WorkerManager.setWindowTitle(_translate("WorkerManager", "Worker Manager"))
        self.groupBox.setTitle(_translate("WorkerManager", "Worker Threads"))
        item = self.workerTable.verticalHeaderItem(0)
        item.setText(_translate("WorkerManager", "1"))
        item = self.workerTable.horizontalHeaderItem(0)
        item.setText(_translate("WorkerManager", "Name"))
        item = self.workerTable.horizontalHeaderItem(1)
        item.setText(_translate("WorkerManager", "Parent"))
        __sortingEnabled = self.workerTable.isSortingEnabled()
        self.workerTable.setSortingEnabled(False)
        item = self.workerTable.item(0, 0)
        item.setText(_translate("WorkerManager", "Example Worker"))
        item = self.workerTable.item(0, 1)
        item.setText(_translate("WorkerManager", "Activity"))
        self.workerTable.setSortingEnabled(__sortingEnabled)
